    version: '3.8'

    services:
      app:
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
          - .:/var/www
        working_dir: /var/www
        environment:
          - DB_CONNECTION=pgsql
          - DB_HOST=db
          - DB_PORT=5432
          - DB_DATABASE=laravel
          - DB_USERNAME=root
          - DB_PASSWORD=root
        networks:
          - app-network

      nginx:
        image: nginx:alpine
        ports:
          - "8000:80"
        volumes:
          - .:/var/www
          - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
          - app
        networks:
          - app-network

      db:
        image: postgres:13-alpine
        volumes:
          - db-data:/var/lib/postgresql/data
        environment:
          - POSTGRES_DB=laravel
          - POSTGRES_USER=root
          - POSTGRES_PASSWORD=root
        ports:
          - "5432:5432"
        networks:
          - app-network

    networks:
      app-network:
        driver: bridge

    volumes:
      db-data:
        driver: local
    